course/06-databases-and-storage/code/arrr/config/routes.rb
Rails.application.routes.draw do
  resources :gadgets

end

course/06-databases-and-storage/code/arrr/app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :widget
end

course/06-databases-and-storage/code/arrr/app/models/widget.rb
class Widget < ActiveRecord::Base
  validates_presence_of :name
end

course/06-databases-and-storage/code/arrr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

course/06-databases-and-storage/code/arrr/app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :set_gadget, only: [:show, :edit, :update, :destroy]

  # GET /gadgets
  # GET /gadgets.json
  def index
    @gadgets = Gadget.all
  end

  # GET /gadgets/1
  # GET /gadgets/1.json
  def show
  end

  # GET /gadgets/new
  def new
    @gadget = Gadget.new
  end

  # GET /gadgets/1/edit
  def edit
  end

  # POST /gadgets
  # POST /gadgets.json
  def create
    @gadget = Gadget.new(gadget_params)

    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Gadget was successfully created.' }
        format.json { render :show, status: :created, location: @gadget }
      else
        format.html { render :new }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gadgets/1
  # PATCH/PUT /gadgets/1.json
  def update
    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Gadget was successfully updated.' }
        format.json { render :show, status: :ok, location: @gadget }
      else
        format.html { render :edit }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gadgets/1
  # DELETE /gadgets/1.json
  def destroy
    @gadget.destroy
    respond_to do |format|
      format.html { redirect_to gadgets_url, notice: 'Gadget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gadget
      @gadget = Gadget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gadget_params
      params.require(:gadget).permit(:name, :widget_id)
    end
end

course/06-databases-and-storage/code/arrr/app/helpers/application_helper.rb
module ApplicationHelper
end

course/06-databases-and-storage/code/arrr/app/helpers/gadgets_helper.rb
module GadgetsHelper
end

course/06-databases-and-storage/code/arrr/app/views/gadgets/_form.html.erb
<%= form_for(@gadget) do |f| %>
  <% if @gadget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gadget.errors.count, "error") %> prohibited this gadget from being saved:</h2>

      <ul>
      <% @gadget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :widget_id %><br>
    <%= f.text_field :widget_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

course/06-databases-and-storage/code/arrr/app/views/gadgets/edit.html.erb
<h1>Editing Gadget</h1>

<%= render 'form' %>

<%= link_to 'Show', @gadget %> |
<%= link_to 'Back', gadgets_path %>

course/06-databases-and-storage/code/arrr/app/views/gadgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gadgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Widget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gadgets.each do |gadget| %>
      <tr>
        <td><%= gadget.name %></td>
        <td><%= gadget.widget %></td>
        <td><%= link_to 'Show', gadget %></td>
        <td><%= link_to 'Edit', edit_gadget_path(gadget) %></td>
        <td><%= link_to 'Destroy', gadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gadget', new_gadget_path %>

course/06-databases-and-storage/code/arrr/app/views/gadgets/new.html.erb
<h1>New Gadget</h1>

<%= render 'form' %>

<%= link_to 'Back', gadgets_path %>

course/06-databases-and-storage/code/arrr/app/views/gadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gadget.name %>
</p>

<p>
  <strong>Widget:</strong>
  <%= @gadget.widget %>
</p>

<%= link_to 'Edit', edit_gadget_path(@gadget) %> |
<%= link_to 'Back', gadgets_path %>

course/06-databases-and-storage/code/arrr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arrr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>